### PR TITLE
Pep621 and other CI

### PR DESCRIPTION
**Pull request by LecrisUT**
Modernizing the project structure and tools

### CODE REVIEW

**Comment by espdev** [comment]
Hello @LecrisUT,

There is a lot of changes. The PR contains multiple unrelated changes: code style, formatting, packaging, CI/CD...

I am not sure I will be able to maintain the project going in its new form. Maybe you want to be a main maintainer of the project?

In any case, unrelated changes are better made by separate PRs.

**Comment by LecrisUT** [comment]
Indeed I've made them separate commits so they are easier to cherry-pick and separate into separate PRs. Let me know which ones you want to separate and prioritize.

I can help with the project management and occasional bug-fix, but I'm not sure if I can help to implement features.

**Comment by LecrisUT** [comment]
Did a few quick edits from the phone. Will rebase them tomorrow.

**Comment by espdev** [comment]
Let's start with change packaging?

1. Packaging. I recommend use Poetry or PDM instead of hatchling.
2. CI/CD. Why do you use Codecov? It seems to me Coveralls is already configured and works fine. Build and publish packages to PyPI from CI/CD (publish in manual mode) is a good idea
3. Formatting, code style, linters. How about use yapf instead of black, also use isort to sort imports and use ruff linter instead of flake8?

**Comment by LecrisUT** [comment]
>     1. Packaging. I recommend use Poetry or PDM instead of hatchling.

It's a bit of an annoyance, but when packaging for LTS distros like RHEL 9 and variants, there were some bugs with setuptools and some other that made hatchling the most viable solution for that. I don't really like `poetry` because it uses it's own standard over PEP621. `PDM` is a possible alternative, but I thought that it doesn't work with dynamic version or some other reason. Had a similar discussion on the `tmt` project.

>     2. CI/CD. Why do you use Codecov? It seems to me Coveralls is already configured and works fine

These were copied from my other projects where I have codecov by default. I'll change it back to coveralls tomorrow.

> Build and publish packages to PyPI from CI/CD (publish in manual mode) is a good idea

Sure, I've had it setup with workflow_dispatch on another project. Do you want it in addition to tag release or to replace it?

>     3. Formatting, code style, linters. How about use yapf instead of black, also use isort to sort imports and use ruff linter instead of flake8?

I think I have reference for ruff and isort. Not sure about yapf though. As long as there are pre-commits for it than sure. I'm experimenting with Qodana that gives mostly the same static analysis as in Pycharm, but it currently seems to have a bug with PEP621.

My reference projects are mainly packit, tmt, and scikit-build-core.

**Comment by LecrisUT** [comment]
- Added back the `Coveralls`
- Previous discussions ([`1`](https://github.com/packit/packit/pull/1913#issuecomment-1499511831), [`2`](https://github.com/teemtee/tmt/issues/2145#issuecomment-1604474663)) were discussing `flit` and not `pdm`. But as I understand PDM also doesn't use PEP621. I am afraid that this could make integration with downsteam (e.g. Fedora) more complicated. E.g. they use [`%pyproject_buildrequires`](https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_build_macros) to pull in the dependencies directly from the `pyproject.toml`, and I'm not sure if it works with pdm lock files. Otherwise what are the features that you want from there that are not available on `hatchling`?

**Comment by espdev** [comment]
> Do you want it in addition to tag release or to replace it?

I think in addition to tags is a good way. We can use GitHub deployment environments also.

> But as I understand PDM also doesn't use PEP621

It seems PDM supports PEP 621, At least that is what it says on their website:
> A PEP 517 build backend.
> PEP 621 project metadata.

Okay, we can use hatchling if it is more convenient for distros packaging. This project is not that complex and has few dependencies, there is no need for any kind of specialty package management via modern powerful tools such as Poetry or PDM.

**Comment by LecrisUT** [comment]
Ok, I've added `ruff` and `yapf`. Is there anything else for this PR?

**Comment by espdev** [comment]
Here are mutually compatible configs for isort and yapf that I use with my work projects:

```toml

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_sort_within_sections = true
force_to_top = ["typing", "pytest"]
line_length = 120

[tool.yapf]
based_on_style = "pep8"
column_limit = 120
blank_line_before_module_docstring = true
coalesce_brackets = false
dedent_closing_brackets = true
split_arguments_when_comma_terminated = true
split_before_dict_set_generator = true
allow_split_before_dict_value = false
```

**Comment by espdev** [comment]
@LecrisUT 

Looks good to me, let's just merge it. :)

**Pull request merged**
